cartesian_ocp:

  dt: 0.01
  horizon_length: 20
  max_iterations: 20 # solver iterations
  has_free_flyer: true

  # Cost weights
  ee_tracking_weight: 100.0
  state_reg_weight: 1.0
  control_reg_weight: 1.0 
  
  # Terminal cost multiplier for the state regularization term
  terminal_weight_multiplier: 10.0

  # Task configuration
  frame_name: "gripper_grasping_frame"
  
  # Default target
  default_target:
    position: [0.5, 0.5, 0.5]  # [x, y, z]
    quaternion: [0.0, 0.0, 0.0, 1.0]  # [x, y, z, w]
